// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Snap & Paint",
    defaultLocalization: "en",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Snap & Paint",
            targets: ["AppModule"],
            bundleIdentifier: "com.usman.snapandpaint",
            teamIdentifier: "C349D5XMPU",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .phone,
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeLeft,
                .landscapeRight
            ],
            capabilities: [
                .camera(purposeString: "Take photos to generate coloring pages."),
                .photoLibrary(purposeString: "Select photos to generate coloring pages."),
                .photoLibraryAdd(purposeString: "Save completed artwork to your Photos.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                "OpenCVBridge"
            ],
            path: "Sources",
            resources: [
                .process("Assets.xcassets"),
                .process("Fonts")
            ]
        ),
        .target(
            name: "OpenCVBridge",
            dependencies: [
                "OpenCVBinary"
            ],
            path: "OpenCVBridge",
            publicHeadersPath: "include",
            cxxSettings: [
                .headerSearchPath("include")
            ]
        ),
        .binaryTarget(
            name: "OpenCVBinary",
            path: "Vendor/OpenCV/opencv2.xcframework"
        )
    ]
)
